---
apiVersion: v1
kind: Pod
metadata:
  name: test-configmap
spec:
  containers:
    - name: test-configmap
      image: nginx:1.13.9-alpine
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level