---
apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath
spec:
  containers:
  - image: nginx:1.13.9-alpine
    name: test-hostpath-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-hostpath-volume
  volumes:
  - name: test-hostpath-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory