---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["pyrex09.metroplex.drhm01.ef86.net"]
            }
          ]}
         ]}
        }'
spec:
  capacity:
    storage: 5Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/vol1

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.9-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: www-volume
          mountPath: /temp/aaa/
      volumes:
        - name: www-volume
          persistentVolumeClaim:
            claimName: www-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: www-pvc
spec:
  storageClassName: local-storage
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Mi