# - ClusterIP: Exposes the service on a cluster-internal IP.
#   Choosing this value makes the service only reachable from
#   within the cluster. This is the default ServiceType.
# - NodePort: Exposes the service on each Node’s IP at a static port (the NodePort).
#   A ClusterIP service, to which the NodePort service will route, is automatically
#   created. You’ll be able to contact the NodePort service, from outside the cluster,
#   by requesting <NodeIP>:<NodePort>.
# - LoadBalancer: Exposes the service externally using a cloud provider’s load balancer.
#   NodePort and ClusterIP services, to which the external load balancer will route,
#   are automatically created.
# - ExternalName: Maps the service to the contents of the externalName field (e.g. foo.bar.example.com),
#   by returning a CNAME record with its value. No proxying of any kind is set up.
#   This requires version 1.7 or higher of kube-dns.

# ClusterIp (Default)
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: MyApp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9377


# NodePort
# the Kubernetes master will allocate a port from a flag-configured range (default: 30000-32767)
# Note that this Service will be visible as both <NodeIP>:spec.ports[*].nodePort and spec.clusterIP:spec.ports[*].port.
# This will cause kubernetes to listen on 30080 and 30443 respectively.
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
  selector:
    name: nginx


# LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  #
  type: LoadBalancer
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  clusterIP: 10.0.171.239
  loadBalancerIP: 78.11.24.19
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155