# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

---
# he following is an example of a Deployment. It creates a ReplicaSet to bring up three nginx Pods:
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  paused: false
  replicas: 3
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.13.9-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80