---
apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulsets
  labels:
    app: nginx-statefulsets
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-statefulsets

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-statefulsets-pv-volume
  labels:
    type: local
spec:
  storageClassName: nginx-statefulsets-classname
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: web-statefulsets
spec:
  selector:
    matchLabels:
      app: nginx-statefulsets # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-statefulsets # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.13.9-alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: nginx-statefulsets-classname
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi